# config.py
SUPABASE_URL = "https://mgicdbgaokksyetwemjr.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1naWNkYmdhb2trc3lldHdlbWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTA2OTksImV4cCI6MjA1OTk2NjY5OX0.JSUQoohut0nIrJFmH3oZZNTLtYZekS22bFcgmT3kX_Y"